import { db } from './index'
import { listings } from './schema'

async function seed() {
  await db.insert(listings).values([
    { ownerId: 'seed-owner-1', title: 'MacBook Air M2', brand: 'Apple', cpu: 'Apple M2', ram: '16GB', storage: '512GB SSD', screen: '13.6"', gpu: null, os: 'macOS', condition: 'Excellent', description: 'Light, fast, perfect for note-taking and everyday coursework.', pickupLocation: 'Voyageur Place', university: 'University of Saskatchewan', dailyPrice: 16, weeklyPrice: 62, monthlyPrice: 165, imageUrl: null, available: true },
    { ownerId: 'seed-owner-2', title: 'MacBook Pro 14" M3', brand: 'Apple', cpu: 'Apple M3', ram: '18GB', storage: '1TB SSD', screen: '14.2"', gpu: null, os: 'macOS', condition: 'Like new', description: 'Great for video editing, heavier coursework, and design projects.', pickupLocation: 'Voyageur Place', university: 'University of Saskatchewan', dailyPrice: 24, weeklyPrice: 90, monthlyPrice: 240, imageUrl: null, available: true },
    { ownerId: 'seed-owner-3', title: 'Dell XPS 15', brand: 'Dell', cpu: 'Intel Core i7-13700H', ram: '32GB', storage: '1TB SSD', screen: '15.6"', gpu: 'RTX 3050', os: 'Windows 11', condition: 'Good', description: 'Handles CAD, SolidWorks, and simulation software without issue.', pickupLocation: 'College Quarter', university: 'University of Saskatchewan', dailyPrice: 20, weeklyPrice: 75, monthlyPrice: 200, imageUrl: null, available: true },
    { ownerId: 'seed-owner-4', title: 'Dell Inspiron 14', brand: 'Dell', cpu: 'Intel Core i5-1235U', ram: '8GB', storage: '256GB SSD', screen: '14"', gpu: null, os: 'Windows 11', condition: 'Good', description: 'Reliable everyday laptop for browsing, writing, and light coursework.', pickupLocation: 'McEown Park', university: 'University of Saskatchewan', dailyPrice: 11, weeklyPrice: 42, monthlyPrice: 110, imageUrl: null, available: true },
    { ownerId: 'seed-owner-5', title: 'Lenovo ThinkPad T14', brand: 'Lenovo', cpu: 'AMD Ryzen 5 7530U', ram: '16GB', storage: '1TB SSD', screen: '14"', gpu: null, os: 'Windows 11', condition: 'Good', description: 'Durable, business-grade build with a great keyboard for long writing sessions.', pickupLocation: 'Engineering Building', university: 'University of Saskatchewan', dailyPrice: 12, weeklyPrice: 48, monthlyPrice: 130, imageUrl: null, available: true },
    { ownerId: 'seed-owner-6', title: 'Lenovo Legion 5', brand: 'Lenovo', cpu: 'AMD Ryzen 7 7735HS', ram: '16GB', storage: '512GB SSD', screen: '15.6"', gpu: 'RTX 4060', os: 'Windows 11', condition: 'Excellent', description: 'Great for rendering, simulations, and demanding engineering software.', pickupLocation: "Louis' Loft", university: 'University of Saskatchewan', dailyPrice: 22, weeklyPrice: 82, monthlyPrice: 220, imageUrl: null, available: true },
    { ownerId: 'seed-owner-7', title: 'HP Pavilion 15', brand: 'HP', cpu: 'Intel Core i5-1155G7', ram: '8GB', storage: '256GB SSD', screen: '15.6"', gpu: null, os: 'Windows 11', condition: 'Fair', description: 'Budget-friendly option, great for a single exam period or short deadline.', pickupLocation: "Louis' Loft", university: 'University of Saskatchewan', dailyPrice: 9, weeklyPrice: 36, monthlyPrice: 98, imageUrl: null, available: true },
    { ownerId: 'seed-owner-8', title: 'HP Spectre x360', brand: 'HP', cpu: 'Intel Core i7-1355U', ram: '16GB', storage: '512GB SSD', screen: '13.5"', gpu: null, os: 'Windows 11', condition: 'Excellent', description: 'Convertible 2-in-1, great for note-taking with a stylus.', pickupLocation: 'College Quarter', university: 'University of Saskatchewan', dailyPrice: 15, weeklyPrice: 58, monthlyPrice: 155, imageUrl: null, available: true },
    { ownerId: 'seed-owner-9', title: 'ASUS ROG Strix G15', brand: 'ASUS', cpu: 'AMD Ryzen 7 7735HS', ram: '16GB', storage: '1TB SSD', screen: '15.6"', gpu: 'RTX 4060', os: 'Windows 11', condition: 'Good', description: 'Strong performance for demanding coursework, simulations, or design work.', pickupLocation: 'McEown Park', university: 'University of Saskatchewan', dailyPrice: 22, weeklyPrice: 82, monthlyPrice: 220, imageUrl: null, available: true },
    { ownerId: 'seed-owner-10', title: 'ASUS ZenBook 14', brand: 'ASUS', cpu: 'Intel Core i5-1340P', ram: '16GB', storage: '512GB SSD', screen: '14"', gpu: null, os: 'Windows 11', condition: 'Excellent', description: 'Slim, light, and quiet — great for daily class use and note-taking.', pickupLocation: 'Voyageur Place', university: 'University of Saskatchewan', dailyPrice: 13, weeklyPrice: 50, monthlyPrice: 135, imageUrl: null, available: true },
    { ownerId: 'seed-owner-11', title: 'Microsoft Surface Laptop 5', brand: 'Microsoft', cpu: 'Intel Core i5-1235U', ram: '8GB', storage: '256GB SSD', screen: '13.5"', gpu: null, os: 'Windows 11', condition: 'Good', description: 'Clean, minimal design, great battery life for full days on campus.', pickupLocation: 'Engineering Building', university: 'University of Saskatchewan', dailyPrice: 14, weeklyPrice: 55, monthlyPrice: 145, imageUrl: null, available: true },
    { ownerId: 'seed-owner-12', title: 'Microsoft Surface Pro 9', brand: 'Microsoft', cpu: 'Intel Core i7-1255U', ram: '16GB', storage: '512GB SSD', screen: '13"', gpu: null, os: 'Windows 11', condition: 'Excellent', description: 'Tablet/laptop hybrid, great for sketching, note-taking, and portability.', pickupLocation: 'College Quarter', university: 'University of Saskatchewan', dailyPrice: 18, weeklyPrice: 68, monthlyPrice: 180, imageUrl: null, available: true },
  ])

  console.log('Seeded 12 listings successfully.')
  process.exit(0)
}

seed().catch((err) => {
  console.error('Seed failed:', err)
  process.exit(1)
}) 